# Generated by Django 6.0 on 2025-12-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
